# Generated by Django 4.1.7 on 2023-02-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passPort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('sex', models.BooleanField()),
                ('native_place', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('save_number', models.CharField(max_length=64)),
                ('valid_date', models.IntegerField()),
                ('brith_date', models.DateField(auto_now=True)),
                ('get_date', models.DateField(auto_now=True)),
                ('out_date', models.DateTimeField(auto_now=True)),
                ('last_date', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField()),
            ],
        ),
    ]
