# Generated by Django 4.1.7 on 2023-02-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passPort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='id',
            new_name='ids',
        ),
    ]
