# Generated by Django 4.1.7 on 2023-02-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passPort', '0002_rename_id_passport_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='ids',
            new_name='id',
        ),
    ]
